project:
  type: website
  resources:
    - images/placeholder.png

brand: tlm-styles/_brand.yml

resources:
  - "**/*.pdf"

website:
  title: "BIOL 490 Field Ornithology"
  navbar:
    search: true
    left:
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
        text: Syllabus
      - href: schedule/index.qmd
        text: Schedule
      - href: homework/index.qmd
        text: Homework
      - text: Field Manual
        menu:
          - href: field-skills/index.qmd
            text: Field Skills
          - href: bird-identification/index.qmd
            text: Bird Identification
          - href: habitats/index.qmd
            text: Habitats
          - href: field-sites/index.qmd
            text: Field Sites
          - href: field-methods/index.qmd
            text: Field Methods
          - href: data-sheets/index.qmd
            text: Data Sheets
      - href: resources/index.qmd
        text: Resources
      
  sidebar:
    style: "docked"
    search: true
    collapse-level: 0
    contents: 
      - href: index.qmd
        text: Home
      - href: syllabus/index.qmd
      - href: schedule/index.qmd
      - href: homework/index.qmd
      - section: "Field Manual"
        contents:
        - href: field-skills/index.qmd
        - href: bird-identification/index.qmd
        - href: habitats/index.qmd
        - href: field-sites/index.qmd
        - href: field-methods/index.qmd
        - href: data-sheets/index.qmd
      - href: resources/index.qmd

format:
  html:
    toc: true
    theme: 
      - default
      - tlm-styles/tlm-theme.scss
      - styles.scss
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://use.typekit.net/tag1lvz.css">

execute:
  echo: false
  warning: false
  message: false
  cache: true
  freeze: auto